version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '80:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - mongo

  mongo:
    image: 'mongo:4.0.7'
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodata:/var/lib/mongodb/data 777

  db:
    build: ./docker/postgres
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data 777
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarydb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5000:80'
    depends_on:
      - db
